<template>
  <div class="deposit_form">
    <table border="0" cellpadding="0" cellspacing="0">
      <tbody><tr>
        <td class="txt">推广网址</td>
        <td class="cl-dd">http://11111.lilai002.com</td>
      </tr>
      </tbody></table>
  </div>
</template>
<script>
    export default {
        name: "",
        data() {
            return {}
        },
        props: {},
        computed: {},
        watch: {},
        methods: {},
        created() {
        },
        activated() {
        },
        components: {}
    }
</script>
<style spcoed>
</style>
